# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f158e50128043620a62d87317aff4d16100b7bf1ba2f640384010f4331b50e4642f30ac177a5f55f99c7a3e157f13ebd9da724666af0f51189e5dfe0a4ada2d0

test:
  secret_key_base: 50d9c161fce823e1cfc0e2caa259832fd2b2c944141e70337578549de77af539d4854934fe952e62ae78609a629e13300779e0fb2093cf51f0e574eaf017aa73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
